version: "2.3"



services:
  test-2.5:
    build:
      context: .
      args:
        RUBY_VERSION: 2.5
    image: bbkutils-tests:2.5
    working_dir: /home/app
    
  test-3.0:
    build:
      context: .
      args:
        RUBY_VERSION: 3.0
    image: bbkutils-tests:3.0
    environment:
      - RBS_TEST_TARGET
      - RUBYOPT
      - RBS_TEST_OPT
    working_dir: /home/app
    
    


