version: "2.3"

x-cache-build: &cb
  context: ${PWD-./}
  dockerfile: Dockerfile.base
  cache_from:
    - gemtestbase:2.5
    - bbk-tests:2.5
    - gemtestbase:3.0
    - bbk-tests:3.0

x-build: &build
  context: ${PWD-./}
  dockerfile: Dockerfile


services:
  gemtestbase-2.5:
    build:
      <<: *cb
      args:
        BASE_IMAGE: ruby:2.5-alpine
        BUILDKIT_INLINE_CACHE: 1
    image: gemtestbase:2.5
    working_dir: /home/app
    
  gemtestbase-3.0:
    build:
      <<: *cb
      args:
        BASE_IMAGE: ruby:3.0-alpine
        BUILDKIT_INLINE_CACHE: 1
    image: gemtestbase:3.0
    working_dir: /home/app

  test-2.5:
    build:
      <<: *build
      args:
        BUILD_TAG: 2.5
        GEM_STORAGE_AUTH: ${NEXUS_AUTH-unknown}
    depends_on:
      - gemtestbase-2.5
    image: bbk-tests:2.5
    working_dir: /home/app
    
  test-3.0:
    build:
      <<: *build
      args:
        BUILD_TAG: 3.0
        GEM_STORAGE_AUTH: ${NEXUS_AUTH-unknown}
    depends_on:
      - gemtestbase-3.0
    image: bbk-tests:3.0
    working_dir: /home/app
    


