version: "2.3"



services:
  test:
    build:
      context: .
      args:
        RUBY_VERSION: ${RUBY_VERSION-3.0}
    image: bbkutils-tests:${RUBY_VERSION-3.0}
    environment:
      - RBS_TEST_TARGET
      - RUBYOPT
      - RBS_TEST_OPT
    working_dir: /home/app
    
    
    


